unjs/mkdist

- src/make.ts
oop! thanks for merging the last PR, but I actually broke things (very sorry)... Should add a test. The regex in #17 matches `export <anything> ""`. which incidentally matches actual exports that contain strings.
```javascript
export const hi = "";
export class Hello {
constructor() {
this.hi = "" <- matched!
}
}
```
I'm very sorry. This PR adds back the `from` in the regex, but also keeps the multi-line matching.
- before: https://regex101.com/r/iJciCA/1
- after: https://regex101.com/r/ukpG5C/1
> critical-fix: multiline regex for exports

- README.md
- src/cli.ts
- src/make.ts
- test/index.test.ts
Related to #18.
This PR adds a new `pattern` option to filter input files. 
The option can be specified in the CLI via the `--pattern` argument.
> feat: support filtering input files with pattern

- package.json
- src/loaders/js.ts
- src/utils/dts.ts
- test/fixture/src/bar/esm.mjs
- test/index.test.ts
- yarn.lock
includes #23, but with a few further fixes
resolves #25
> fix: support emitting `.d.mts` for `.mjs` files

- README.md
- src/cli.ts
- src/make.ts
- test/index.test.ts
This PR iterates over #21. 
The `globby` library supports an array with multiple globs as its first argument, and `mri` already supports multiple inputs for a flag (`--pattern=aaa --pattern=bbb --> pattern: ['aaa', 'bbb']`). 
Adding the ability to pass multiple patterns makes it easier to use negative patterns and create more complex filters. 
On the documentation, I am not sure whether the `[--pattern=glob [--pattern=more-glob]]` signature is correct or if there is a clearer way to express the feature.
> feat: support multiple glob patterns

- src/loaders/sass.ts
- test/fixture/src/demo.scss
- test/index.test.ts
This PR should fix https://github.com/nuxt/module-builder/issues/67 by forcing sass input files to be always outputted with a `.css` extension.
The code has been extracted from https://github.com/unjs/mkdist/pull/109 for easier review.
> fix: ensure sass output file has css extension

- src/make.ts
Fixes #45 and https://github.com/unjs/unbuild/issues/83.
The change essentially does the following:
- One-line imports are handled as they were before
- Multi-line imports are handled only if brackets are present, allowing full control over the multi-line capture group, so that we don't mistakenly capture functions and objects that use brackets.
The simplest solution of using `[\s\S]` instead of `.*` will spill over to `export function() {}` and `export {};`, therefore it's not feasible.
> fix: add support for multi-line import extension normalization

- src/make.ts
resolves https://github.com/unjs/mkdist/issues/137
related: https://github.com/nuxt/nuxt/issues/19689
Our regexp already guards against replacing in CJS files, and we already resolve `.js` files within esm, so I think this is a safe change to make.
> feat: add support for relativising type exports

- src/loader.ts
- src/loaders/js.ts
- src/make.ts
- test/index.test.ts
This pr is related to issue: #39 
add esbuildOptions as prop to createLoader thus can make jsLoader using custom esbuild options while doing esbuild transform:
> feat: allow passing esbuild transform options

- src/cli.ts
- src/loader.ts
- src/loaders/index.ts
- src/loaders/js.ts
- src/make.ts
- test/index.test.ts
Pick and choose the loaders mkdist uses. This (theoretically) resolves #128, as one would be able to only include jsLoader and vueLoader. This would also be a good step in resolving nuxt/module-builder#90.
Adding that import for all the loaders in make.ts made the builder fuss up, I think I fixed that by giving jiti an empty string. I tried to implement this as elegantly as I could; hopefully this at least brings attention to the issue.
> feat: support configurable loaders

- src/loaders/js.ts
- test/fixture/src/ts/test1.mts
- test/fixture/src/ts/test2.cts
- test/index.test.ts
Resolves #138
Handle `.cts` and `.mts` as typescript sources and generate them into the output
> fix: handle `.cts` and `.mts` as typescript

- README.md
- package.json
- pnpm-lock.yaml
- src/loader.ts
- src/loaders/index.ts
- src/loaders/postcss.ts
- src/loaders/vue.ts
- test/fixture/src/components/blank.vue
- test/fixture/src/nested.css
- test/index.test.ts
Resolves #166
TODO: Before introducing this feature i am thinking to make the plugins configurable and (some?) opt-in. 
Beta testing: Add this to `package.json` and run install command. It should work directly for mkdist and also for unbuild, nuxt-module-builder, etc.
```json
"resolutions": {
"mkdist": "npm:@pi0/mkdist@1.4.0-rc.2"
},
```
Thoughts welcome 👍🏼
> feat: support postcss loader

- package.json
- pnpm-lock.yaml
- src/utils/vue-dts.ts
- test/index.test.ts
closes https://github.com/unjs/mkdist/pull/199
A few days ago, [vue/language-tools](https://github.com/vuejs/language-tools) updated its main version to 2.x.x, and vue-tac no longer provides the `createProgram` function in v2, so it needs to be rewritten to be used.
> feat: support vue-tsc v2

- src/make.ts
- src/utils/dts.ts
https://github.com/nuxt/module-builder/issues/297
https://github.com/nuxt/module-builder/issues/299
Previously we were rather naively normalising tsconfig options but we do have the ability to do that from ts itself.
> fix(dts): use `ts.convertCompilerOptionsFromJson` to normalise

- package.json
- pnpm-lock.yaml
- src/make.ts
Under the hood, `globby` is powered by `fast-glob` with extra features, but none of them are utilized by the `mkdist`.
Since the `mkdist` doesn't utilize those extra features, the PR replaces `globby` with `fast-glob` to reduce the installation size.
See also https://github.com/unjs/unbuild/pull/418, https://github.com/typescript-eslint/typescript-eslint/issues/9453
> refactor: replace globby w/ fast-glob

- package.json
- pnpm-lock.yaml
- src/utils/vue-dts.ts
- test/index.test.ts
Resolves #239 
add support for `vue-tsc >= 2.1.2`, and add a test to make sure it wouldn't break the builds with `~2.0.21`
**Additional**
I notice that the test case of `vue-tsc@^1` didn't do the right test so I also fix it in this pr.
> fix(dts): compatible with vue-tsc 2.1.2

- package.json
- pnpm-lock.yaml
- src/utils/vue-dts.ts
- test/index.test.ts
Fixed [Comment in #240](https://github.com/unjs/mkdist/pull/240#issuecomment-2326976000) 
This PR fixes forward compatibility with `vue-tsc@~2.0.12` and the wrong test case, now mkdist should work well with all vue-tsc matching the peerDependence requirement.
> fix(dts): compatible with `vue-tsc` 2.0.x

- src/loaders/vue.ts
- test/fixture/src/components/script-multi-block.vue
- test/index.test.ts
`mkdist` currently only transforms first block of each type in vue files.
This is a hotfix to handle an issue where the first `<script>` block is transpiled, and the second one isn't, which yields a vue compiler error (because `lang` should match between script blocks).
We would need to support handling multiple script blocks in future.
related: https://github.com/unjs/mkdist/issues/209
> fix(vue): skip transpilation with multiple script blocks

- src/utils/dts.ts
- test/fixture/src/dir-export.ts
- test/index.test.ts
resolves https://github.com/nuxt/module-builder/issues/308
with directory indices, currently we output a JS file like this:
```ts
export * from "./star/index.mjs";
```
and a declaration like this:
```ts
export * from "./star.mjs";
```
This PR normalises the DTS generation so both have `/index` appended.
> fix(dts): resolve directory exports in `.dts` files

- src/utils/dts.ts
- test/fixture/src/bar.ts
- test/fixture/src/dir-export.ts
- test/index.test.ts
resolves https://github.com/unjs/mkdist/pull/244#discussion_r1752209500
> fix(dts): handle dir + file of same name

- src/make.ts
resolves https://github.com/nuxt/module-builder/issues/400
Might be worth more discussion about whether this is desired, or a breaking change.
(Nevertheless it should be possible to override by using an array pattern syntax to exclude files matching a dot pattern. Alternatively, we could allow configuring glob options more specifically - but it feels like the pattern syntax is a safer API.)
> fix: scan dotfiles in source paths

- package.json
- src/loaders/vue.ts
- src/utils/vue-dts.ts
- test/fixture/src/components/script-setup-ts.vue
- test/fixture/src/prop-types/index.ts
- test/fixture/tsconfig.json
- test/index.test.ts
Refactor the vue loader with vue/compiler-sfc.
Resolve #209 #249 #243 #14 #15 
Close #210 
Some break changes:
- Since there is no effective way to confirm the position of blocks, all blocks will be reordered after build. (unless it can be quick return)
- The script blocks will look a little (?) different from source if developer uses `<script setup lang="*">`, but they are still human readable
- see https://github.com/unjs/mkdist/pull/251#discussion_r1827009276
But I think it is worth.
also updated test.
------
~~It is a draft pull request because I found some times `vue-tsc^2.1.0` will add the vue global declare in dts output for no resaon.~~
~~It happens in my own package [Teages/mkdist-vue-loader](https://github.com/Teages/mkdist-vue-loader) but after I merged back to mkdist it …
> feat(vue)!: refactor vue loader with vue/compiler-sfc

- src/make.ts
Related to #265
There are situations when we want to customize glob options. Mainly I find cases that there might be generated + ignored files in src and this gives an escape hatch.
> feat: support `globOptions`

- src/make.ts
repro: https://github.com/unjs/unstorage/pull/523
With #253, we started to scan dotfiles and ignore git ignored paths however it makes issues since globby accepts globs `/path` means absolute path in gitignore `/path` means `<gitDir>/path`.
> fix: convert absolute gitignore patterns to relative

- src/loader.ts
- src/make.ts
- src/utils/dts.ts
- src/utils/vue-dts.ts
- test/index.test.ts
It's possible for compiler errors to occur when processing individual declarations - this causes empty files which will (silently) break builds.
This exposes an `errors` object which can be handled by builders like `unbuild` to throw an error and fail the build in this case, if so configured. (It does not change default behaviour.)
While debugging, I removed the incorrect `incremental` compiler option and added the more permissive `allowImportingTsExtensions`.
> feat(dts): expose ts compiler errors

- src/make.ts
Relavant issues: #265, https://github.com/unjs/unbuild/issues/472
This PR replaces problematic gitignore inferences with only known patterns `["**/node_modules", "**/coverage", "**/.git"]` (same as `globby` defaults)
Context: #253 enabled dotfiles scanning and at the same time we added a small solution to infer gitignore patterns. however, it is problematic because `tinyglobby` unlike `globby` does not natively has gitignore support and gitignore patterns are not same as glob patterns (#265)
This PR is an alternative to #271 because even if using [ignore](https://www.npmjs.com/package/ignore) util, we need to convert scanned paths to be relative from root before matching (which is likely to have more edge cases), we need nested gitignore support and on top of all this, it still breaks …
> fix: only add known ignore patterns by default
